DOMAIN = "emmesteel"

CMD_EMPTY = ""
CMD_ON_OFF = "on-off"
CMD_POWER_UP = "power-up"
CMD_POWER_DN = "power-dn"
CMD_TIMER_ON_OFF = "crono-off-on"

STATE_ON_OFF = "ON_OFF"
#  0: ON/OFF status
STATE_LED_ON_OFF = "LED_ON_OFF"
#  1: Thermostate LED status
STATE_LEVEL = "LEVEL"
#  2: Power Level
STATE_THERMO_DESIRED_TEMPERATURE_C = "THERMO_DESIRED_TEMPERATURE_C"
#  3: Desired Temperature Set Point
STATE_THERMOSTAT_TEMPERATURE_C = "THERMOSTAT_TEMPERATURE_C"
#  4: Display probe value (0-255)
STATE_THERMOSTAT_ON_OFF = "THERMOSTAT_ON_OFF"
#  5: Enable probe/thermostatat
STATE_SWITCH_THERMOSTAT_ENABLED = "SWITCH_THERMOSTAT_ENABLED"
#  6: enable thermostate - when enabled, manual level contro is disabled
STATE_SWITCH_TIMER_ENABLED = "SWITCH_TIMER_ENABLED"
#  7: TIMER ON/OFF status
STATE_TIMER_REMAINING_HOURS = "TIMER_REMAINING_HOURS"
#  8: Timer Hours
STATE_TIMER_REMAINING_MINUTES = "TIMER_REMAINING_MINUTES"
#  9: Timer Minutes
STATE_TIMER_REMAINING_SECONDS = "TIMER_REMAINING_SECONDS"
#  10: TImer Seconds
STATE_CASA_ON_OFF = "CASA_ON_OFF"
#  11: Heating ON/OFF Status

KEY_MAP = {
    "0": STATE_ON_OFF,
    "1": STATE_LED_ON_OFF,
    "2": STATE_LEVEL,  # f"LIVELLO-{valore}.png"
    "3": STATE_THERMO_DESIRED_TEMPERATURE_C,
    "4": STATE_THERMOSTAT_TEMPERATURE_C,
    "5": STATE_THERMOSTAT_ON_OFF,
    "6": STATE_SWITCH_THERMOSTAT_ENABLED,
    "7": STATE_SWITCH_TIMER_ENABLED,
    "8": STATE_TIMER_REMAINING_HOURS,
    "9": STATE_TIMER_REMAINING_MINUTES,
    "10": STATE_TIMER_REMAINING_SECONDS,
    "11": STATE_CASA_ON_OFF,
}
